name: knife_hit
description: "Casual knife throwing game inspired by Knife Hit."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flame: ^1.7.0
  flame_audio: ^2.11.11
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
#  privacy_plugin:
#    git:
#      url: https://gitlab.com/casino-slots/webview-plugin.git
#      ref: privacy_plugin_no_appsflyer

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
  - assets/icon/
  - assets/images/
  - assets/images/backgrounds/
  - assets/images/buttons/
  - assets/fonts/
  - assets/images/targets/
  - assets/images/knives/
  - assets/audio/achievement_unlock.wav
  - assets/audio/apple_hit.wav
  - assets/audio/boss_appear.wav
  - assets/audio/boss_defeat.wav
  - assets/audio/button_click.wav
  - assets/audio/game_over.wav
  - assets/audio/knife_hit.wav
  - assets/audio/knife_miss.wav
  - assets/audio/knife_throw.wav
  - assets/audio/knife_unlock.wav
  - assets/audio/level_complete.wav
  - assets/audio/music/menu_music.mp3
  - assets/audio/music/game_music.mp3
  - assets/audio/music/boss_music.mp3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.jpg"
  adaptive_icon_background: "#FFFFFF00"
  adaptive_icon_foreground: "assets/icon/icon.jpg"